# Specify the base image
FROM node:lts

# Set the working directory inside the container
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Bundle app source inside Docker image
COPY . .

# Your app binds to port 5174 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 5174

# Watch for changes
CMD ["pnpm", "run", "dev"]
