# ========= Development ========= # 
dev-build:
	docker-compose -p indigov build app

dev-up:
	docker-compose -p indigov up --build app

dev-run:
	docker-compose -p indigov up app

dev-down:
	docker-compose -p indigov down
